# Generated by Django 4.2.3 on 2023-09-20 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_general_keys_modelo'),
    ]

    operations = [
        migrations.CreateModel(
            name='tabela_Estoque_WindowsKeys',
            fields=[
                ('idkey', models.AutoField(primary_key=True, serialize=False)),
                ('pv', models.CharField(max_length=50)),
                ('keycontent', models.CharField(max_length=29)),
                ('serialcontent', models.CharField(max_length=30)),
                ('keystate', models.IntegerField()),
                ('bancada', models.CharField(max_length=2)),
                ('disco', models.IntegerField()),
                ('memoria', models.IntegerField()),
                ('data', models.DateField()),
                ('so', models.CharField(default='vazio', max_length=100)),
                ('marca', models.CharField(default='vazio', max_length=100)),
                ('modelo', models.CharField(default='vazio', max_length=100)),
            ],
            options={
                'db_table': 'tabela_Estoque_WindowsKeys',
            },
        ),
    ]
