# Generated by Django 4.2.3 on 2023-09-20 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_tabela_estoque_windowskeys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabela_estoque_windowskeys',
            name='keystate',
            field=models.IntegerField(default=0),
        ),
    ]
