# Generated by Django 4.2.3 on 2023-09-20 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_tabela_estoque_windowskeys_keystate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabela_estoque_windowskeys',
            name='data',
            field=models.DateField(default=0),
        ),
        migrations.AlterField(
            model_name='tabela_estoque_windowskeys',
            name='disco',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tabela_estoque_windowskeys',
            name='memoria',
            field=models.IntegerField(default=0),
        ),
    ]
