# Generated by Django 4.2.3 on 2023-09-20 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_tabela_estoque_windowskeys_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabela_estoque_windowskeys',
            name='data',
            field=models.DateField(auto_now_add=True),
        ),
    ]
