# Generated by Django 4.2.3 on 2023-09-20 15:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_tabela_estoque_windowskeys_nota_fiscal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='general_keys',
            name='Nota_Fiscal',
            field=models.CharField(default=datetime.datetime(2023, 9, 20, 15, 52, 40, 644507, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='general_keys',
            name='PeCom',
            field=models.CharField(default=datetime.datetime(2023, 9, 20, 15, 52, 51, 299718, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tabela_backup',
            name='Nota_Fiscal',
            field=models.CharField(default=datetime.datetime(2023, 9, 20, 15, 52, 56, 111526, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tabela_backup',
            name='PeCom',
            field=models.CharField(default=datetime.datetime(2023, 9, 20, 15, 53, 2, 783518, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
    ]
