# Generated by Django 4.2.3 on 2023-09-20 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_tabela_chaves_duplicadas'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabela_estoque_windowskeys',
            name='uf',
            field=models.CharField(default='vazio', max_length=100),
        ),
    ]
