# Generated by Django 4.2.3 on 2023-09-20 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_tabela_estoque_windowskeys_uf'),
    ]

    operations = [
        migrations.AddField(
            model_name='general_keys',
            name='uf',
            field=models.CharField(default='vazio', max_length=100),
        ),
        migrations.AddField(
            model_name='tabela_backup',
            name='uf',
            field=models.CharField(default='vazio', max_length=100),
        ),
        migrations.AddField(
            model_name='tabela_chaves_duplicadas',
            name='uf',
            field=models.CharField(default='vazio', max_length=100),
        ),
    ]
