# Generated by Django 4.2.3 on 2023-09-25 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_general_keys_uf_tabela_backup_uf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabela_chaves_duplicadas',
            name='keycontent',
            field=models.CharField(max_length=29, unique=True),
        ),
    ]
