# Generated by Django 4.2.3 on 2023-09-25 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_tabela_chaves_duplicadas_keycontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='general_keys',
            name='keycontent',
            field=models.CharField(max_length=29, unique=True),
        ),
        migrations.AlterField(
            model_name='tabela_backup',
            name='keycontent',
            field=models.CharField(max_length=29, unique=True),
        ),
        migrations.AlterField(
            model_name='tabela_estoque_windowskeys',
            name='keycontent',
            field=models.CharField(max_length=29, unique=True),
        ),
    ]
