# Generated by Django 4.2.3 on 2023-09-25 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_general_keys_keycontent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabela_chaves_duplicadas',
            name='keycontent',
            field=models.CharField(max_length=29),
        ),
    ]
