# Generated by Django 4.2.3 on 2023-09-29 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_tabela_chaves_duplicadas_keycontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabela_chaves_duplicadas',
            name='data_duplicada',
            field=models.CharField(default='vazio', max_length=50),
        ),
    ]
