# Generated by Django 4.2.3 on 2023-10-05 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_tabela_chaves_duplicadas_data_duplicada'),
    ]

    operations = [
        migrations.CreateModel(
            name='quantidade_maquinas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantidade', models.IntegerField()),
                ('pv', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'quantidade_maquinas',
            },
        ),
    ]
