# Generated by Django 4.2.3 on 2023-11-03 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_quantidade_maquinas'),
    ]

    operations = [
        migrations.CreateModel(
            name='estoque_office',
            fields=[
                ('idkey', models.AutoField(primary_key=True, serialize=False)),
                ('Nota_Fiscal', models.CharField(max_length=100)),
                ('PeCom', models.CharField(max_length=100)),
                ('keycontent', models.CharField(max_length=29, unique=True)),
                ('data', models.DateField(auto_now_add=True)),
                ('uf', models.CharField(default='vazio', max_length=100)),
            ],
            options={
                'db_table': 'estoque_office',
            },
        ),
        migrations.CreateModel(
            name='general_keys_office',
            fields=[
                ('idkey', models.AutoField(primary_key=True, serialize=False)),
                ('pv', models.CharField(max_length=50)),
                ('Nota_Fiscal', models.CharField(max_length=100)),
                ('PeCom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('senha', models.CharField(max_length=128)),
                ('keycontent', models.CharField(max_length=29, unique=True)),
                ('serialcontent', models.CharField(max_length=30)),
                ('keystate', models.IntegerField()),
                ('bancada', models.CharField(max_length=2)),
                ('disco', models.IntegerField()),
                ('memoria', models.IntegerField()),
                ('data', models.DateField(auto_now_add=True)),
                ('version_office', models.CharField(default='vazio', max_length=100)),
                ('uf', models.CharField(default='vazio', max_length=100)),
                ('marca', models.CharField(default='vazio', max_length=100)),
                ('modelo', models.CharField(default='vazio', max_length=100)),
            ],
            options={
                'db_table': 'general_keys_office',
            },
        ),
        migrations.CreateModel(
            name='tabela_backup_office',
            fields=[
                ('idkey', models.AutoField(primary_key=True, serialize=False)),
                ('pv', models.CharField(max_length=50)),
                ('Nota_Fiscal', models.CharField(max_length=100)),
                ('PeCom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('senha', models.CharField(max_length=128)),
                ('keycontent', models.CharField(max_length=29, unique=True)),
                ('serialcontent', models.CharField(max_length=30)),
                ('keystate', models.IntegerField()),
                ('bancada', models.CharField(max_length=2)),
                ('disco', models.IntegerField()),
                ('memoria', models.IntegerField()),
                ('data', models.DateField()),
                ('version_office', models.CharField(default='vazio', max_length=100)),
                ('uf', models.CharField(default='vazio', max_length=100)),
                ('marca', models.CharField(default='vazio', max_length=100)),
                ('modelo', models.CharField(default='vazio', max_length=100)),
            ],
            options={
                'db_table': 'tabela_backup_office',
            },
        ),
        migrations.CreateModel(
            name='tabela_Chaves_Duplicadas_Office',
            fields=[
                ('idkey', models.AutoField(primary_key=True, serialize=False)),
                ('pv', models.CharField(default='vazio', max_length=50)),
                ('keycontent', models.CharField(max_length=29)),
                ('serialcontent', models.CharField(max_length=30)),
                ('keystate', models.IntegerField(default=0)),
                ('bancada', models.CharField(max_length=2)),
                ('disco', models.IntegerField(default=0)),
                ('memoria', models.IntegerField(default=0)),
                ('data', models.DateField(auto_now_add=True)),
                ('data_duplicada', models.CharField(default='vazio', max_length=50)),
                ('so', models.CharField(default='vazio', max_length=100)),
                ('uf', models.CharField(default='vazio', max_length=100)),
                ('marca', models.CharField(default='vazio', max_length=100)),
                ('modelo', models.CharField(default='vazio', max_length=100)),
                ('Nota_Fiscal', models.CharField(max_length=100)),
                ('PeCom', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tabela_Chaves_Duplicadas_Office',
            },
        ),
    ]
